name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - psutil
  - toolz
  - matplotlib
  - dill
  - partd
  - bokeh
  - dask
  - scikit-learn
  - seaborn
  - time
  